addons:
  apt:
    packages:
      - nodejs
language: python
sudo: false
python:
  - 3.5
  - 3.8
env:
  - TOX_ENV=csslint
  - TOX_ENV=django22
  - TOX_ENV=eslint
  - TOX_ENV=pycodestyle
  - TOX_ENV=pylint
before_install:
  - pip install pip==20.0.2
  - export BOTO_CONFIG=/dev/null
cache:
  directories:
    - $HOME/.cache/pip
install:
  - "make requirements"
  - "pip install codecov"
script:
  - tox -e $TOX_ENV
after_success: codecov
